### PR TITLE
NeedIt Application with Forms

### PR DESCRIPTION
**Pull request by pselker2**

### CODE REVIEW

**Comment by pselker2** [comment]
Merge the master with the additions from the training

**Comment by bsweets** [comment]
Thanks for submitting this, but we do not accept pull requests against the ServiceNow training master repository. As detailed in the module Exercises, you should connect your Studio instance to your own forked copy of the repository and not the ServiceNow master repo. Your work has not been saved to the ServiceNow master repository.  

These videos on the ServiceNow Developers YouTube channel explain how to configure to point to your forked copy of the repository and to troubleshoot setup issues:
https://www.youtube.com/playlist?list=PL3rNcyAiDYK32S3PiD5v4Esv5OcqdRZx1

**Comment by pselker2** [comment]
Hi Ben,

I was not sure of what I was doing in GitHub and I did not intentionally try to merge my branch into the training repo.  I realized after the merge failed, what I was attempting to do.

Regards,
Phil

**Comment by bsweets** [comment]
Hi Phil,
No worries. We wanted to let you know what's going on and how to address it so you do not keep trying to commit an wonder why you can't. Please let us know if you have any other issues trying to get your repository pointing to the right place. If you could, though, please submit the feedback with your request for more help from a training page on the Developer Portal. That better helps us track when people have questions.

I hope you are enjoying the training.

Happy developing,
Ben

**Pull request closed without merging**
